package sidev.lib.`val`

object SuppressLiteral {
    const val UNCHECKED_CAST= "UNCHECKED_CAST"
    const val UNCHECKED_CAST_TO_EXTERNAL_INTERFACE= "UNCHECKED_CAST_TO_EXTERNAL_INTERFACE"
    const val IMPLICIT_CAST_TO_ANY= "IMPLICIT_CAST_TO_ANY"
    const val UNREACHABLE_CODE= "UNREACHABLE_CODE"
    const val PARAMETER_NAME_CHANGED_ON_OVERRIDE= "PARAMETER_NAME_CHANGED_ON_OVERRIDE"
    const val DEPRECATION= "DEPRECATION"
    const val EMPTY_BODY_CONTROL_FLOW= "ControlFlowWithEmptyBody"
    const val NAME_SHADOWING= "NAME_SHADOWING"
    const val EXTENSION_SHADOWED_BY_MEMBER= "EXTENSION_SHADOWED_BY_MEMBER"
}