package sidev.lib.universal.`val`

object SuppressLiteral {
    const val UNCHECKED_CAST= "UNCHECKED_CAST"
    const val UNCHECKED_CAST_TO_EXTERNAL_INTERFACE= "UNCHECKED_CAST_TO_EXTERNAL_INTERFACE"
    const val IMPLICIT_CAST_TO_ANY= "IMPLICIT_CAST_TO_ANY"
    const val UNREACHABLE_CODE= "UNREACHABLE_CODE"
    const val PARAMETER_NAME_CHANGED_ON_OVERRIDE= "PARAMETER_NAME_CHANGED_ON_OVERRIDE"
    const val DEPRECATION= "DEPRECATION"
}